wandb_version: 1

batch_normalisation:
  value: 'True'
batch_size:
  value: 32
data_augmentation:
  value: 'True'
dropout:
  value: 0.3
filter_multiplier:
  value: 0.5
kernel_size:
  value: 3
n_filters:
  value: 256
