wandb_version: 1

batch_normalisation:
  value: 'True'
batch_size:
  value: 32
data_augmentation:
  value: 'True'
dropout:
  value: 0.3
filter_multiplier:
  value: 1
kernel_size:
  value: 5
n_filters:
  value: 256
