wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712422735.158523
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
batch_normalisation:
  desc: null
  value: 'True'
batch_size:
  desc: null
  value: 32
data_augmentation:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.2
filter_multiplier:
  desc: null
  value: 2
kernel_size:
  desc: null
  value: 3
n_filters:
  desc: null
  value: 256
